export type PropertyLead = {
  id: string;
  title: string;
  price: number;
  lotSize: string;
  acres: number;
  city: string;
  state: string;
  county: string;
  listedDate: string;
  sellerName: string;
  sellerCompany: string;
  sellerEmail: string;
  sellerPhone: string;
  zoning: string;
  roadAccess: string;
  utilities: string;
  propertyType: string;
  summary: string;
  highlights: string[];
  dueDiligence: string[];
};

export const MOCK_PROPERTY_LEADS: PropertyLead[] = [
  {
    id: 'austin-tx-0-24-acres',
    title: '0.24 acres in Austin, TX',
    price: 115000,
    lotSize: '0.24 acres',
    acres: 0.24,
    city: 'Austin',
    state: 'TX',
    county: 'Travis',
    listedDate: '2026-08-28',
    sellerName: 'Maria Santos',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'maria.santos@example.com',
    sellerPhone: '(512) 555-1000',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Austin. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Austin market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'denver-co-6-250-sq-ft',
    title: '6,250 sq ft in Denver, CO',
    price: 189000,
    lotSize: '6,250 sq ft',
    acres: 0.14,
    city: 'Denver',
    state: 'CO',
    county: 'Denver',
    listedDate: '2026-08-27',
    sellerName: 'Jason Miller',
    sellerCompany: 'Front Range Parcel Co.',
    sellerEmail: 'jason.miller@example.com',
    sellerPhone: '(303) 555-1001',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Denver. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Denver market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'bend-or-1-91-acres',
    title: '1.91 acres in Bend, OR',
    price: 275000,
    lotSize: '1.91 acres',
    acres: 1.91,
    city: 'Bend',
    state: 'OR',
    county: 'Deschutes',
    listedDate: '2026-08-26',
    sellerName: 'Avery Collins',
    sellerCompany: 'Cascade Land Advisors',
    sellerEmail: 'avery.collins@example.com',
    sellerPhone: '(541) 555-1002',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Bend. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Bend market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'phoenix-az-5-000-sq-ft',
    title: '5,000 sq ft in Phoenix, AZ',
    price: 72000,
    lotSize: '5,000 sq ft',
    acres: 0.11,
    city: 'Phoenix',
    state: 'AZ',
    county: 'Maricopa',
    listedDate: '2026-08-25',
    sellerName: 'Nolan Price',
    sellerCompany: 'Desert Lots Direct',
    sellerEmail: 'nolan.price@example.com',
    sellerPhone: '(602) 555-1003',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Phoenix. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Phoenix market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'charlotte-nc-0-72-acres',
    title: '0.72 acres in Charlotte, NC',
    price: 149500,
    lotSize: '0.72 acres',
    acres: 0.72,
    city: 'Charlotte',
    state: 'NC',
    county: 'Mecklenburg',
    listedDate: '2026-08-24',
    sellerName: 'Keisha Grant',
    sellerCompany: 'Queen City Land Partners',
    sellerEmail: 'keisha.grant@example.com',
    sellerPhone: '(704) 555-1004',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Charlotte. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Charlotte market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'boise-id-2-35-acres',
    title: '2.35 acres in Boise, ID',
    price: 325000,
    lotSize: '2.35 acres',
    acres: 2.35,
    city: 'Boise',
    state: 'ID',
    county: 'Ada',
    listedDate: '2026-08-23',
    sellerName: 'Trevor Hunt',
    sellerCompany: 'Intermountain Dirt Co.',
    sellerEmail: 'trevor.hunt@example.com',
    sellerPhone: '(208) 555-1005',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Boise. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Boise market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'raleigh-nc-0-48-acres',
    title: '0.48 acres in Raleigh, NC',
    price: 132000,
    lotSize: '0.48 acres',
    acres: 0.48,
    city: 'Raleigh',
    state: 'NC',
    county: 'Wake',
    listedDate: '2026-08-22',
    sellerName: 'Dana Whitaker',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'dana.whitaker@example.com',
    sellerPhone: '(919) 555-1006',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Raleigh. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Raleigh market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'tampa-fl-0-75-acres',
    title: '0.75 acres in Tampa, FL',
    price: 210000,
    lotSize: '0.75 acres',
    acres: 0.75,
    city: 'Tampa',
    state: 'FL',
    county: 'Hillsborough',
    listedDate: '2026-08-21',
    sellerName: 'Luis Moreno',
    sellerCompany: 'Gulf Coast Land Co.',
    sellerEmail: 'luis.moreno@example.com',
    sellerPhone: '(813) 555-1007',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Tampa. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Tampa market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'nashville-tn-0-32-acres',
    title: '0.32 acres in Nashville, TN',
    price: 185000,
    lotSize: '0.32 acres',
    acres: 0.32,
    city: 'Nashville',
    state: 'TN',
    county: 'Davidson',
    listedDate: '2026-08-20',
    sellerName: 'Harper Reed',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'harper.reed@example.com',
    sellerPhone: '(615) 555-1008',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Nashville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Nashville market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'san-antonio-tx-1-25-acres',
    title: '1.25 acres in San Antonio, TX',
    price: 98000,
    lotSize: '1.25 acres',
    acres: 1.25,
    city: 'San Antonio',
    state: 'TX',
    county: 'Bexar',
    listedDate: '2026-08-19',
    sellerName: 'Owen Keller',
    sellerCompany: 'Lone Star Dirt Partners',
    sellerEmail: 'owen.keller@example.com',
    sellerPhone: '(210) 555-1009',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in San Antonio. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['San Antonio market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'colorado-springs-co-2-10-acres',
    title: '2.10 acres in Colorado Springs, CO',
    price: 165000,
    lotSize: '2.10 acres',
    acres: 2.1,
    city: 'Colorado Springs',
    state: 'CO',
    county: 'El Paso',
    listedDate: '2026-08-18',
    sellerName: 'Maya Brooks',
    sellerCompany: 'Pikes Peak Property Leads',
    sellerEmail: 'maya.brooks@example.com',
    sellerPhone: '(512) 555-1010',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Colorado Springs. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Colorado Springs market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'savannah-ga-6-800-sq-ft',
    title: '6,800 sq ft in Savannah, GA',
    price: 59000,
    lotSize: '6,800 sq ft',
    acres: 0.16,
    city: 'Savannah',
    state: 'GA',
    county: 'Chatham',
    listedDate: '2026-08-17',
    sellerName: 'Elliot Banks',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'elliot.banks@example.com',
    sellerPhone: '(303) 555-1011',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Savannah. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Savannah market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'las-vegas-nv-0-44-acres',
    title: '0.44 acres in Las Vegas, NV',
    price: 124000,
    lotSize: '0.44 acres',
    acres: 0.44,
    city: 'Las Vegas',
    state: 'NV',
    county: 'Clark',
    listedDate: '2026-08-16',
    sellerName: 'Camila Torres',
    sellerCompany: 'Silver State Lots',
    sellerEmail: 'camila.torres@example.com',
    sellerPhone: '(541) 555-1012',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Las Vegas. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Las Vegas market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'spokane-wa-5-17-acres',
    title: '5.17 acres in Spokane, WA',
    price: 119000,
    lotSize: '5.17 acres',
    acres: 5.17,
    city: 'Spokane',
    state: 'WA',
    county: 'Spokane',
    listedDate: '2026-08-15',
    sellerName: 'Graham Ellis',
    sellerCompany: 'Northwest Acreage Group',
    sellerEmail: 'graham.ellis@example.com',
    sellerPhone: '(602) 555-1013',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Spokane. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Spokane market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'orlando-fl-0-22-acres',
    title: '0.22 acres in Orlando, FL',
    price: 83500,
    lotSize: '0.22 acres',
    acres: 0.22,
    city: 'Orlando',
    state: 'FL',
    county: 'Orange',
    listedDate: '2026-08-14',
    sellerName: 'Priya Shah',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'priya.shah@example.com',
    sellerPhone: '(704) 555-1014',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Orlando. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Orlando market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'greenville-sc-1-10-acres',
    title: '1.10 acres in Greenville, SC',
    price: 89500,
    lotSize: '1.10 acres',
    acres: 1.1,
    city: 'Greenville',
    state: 'SC',
    county: 'Greenville',
    listedDate: '2026-08-13',
    sellerName: 'Noah Bennett',
    sellerCompany: 'Upstate Land Buyers LLC',
    sellerEmail: 'noah.bennett@example.com',
    sellerPhone: '(208) 555-1015',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Greenville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Greenville market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'knoxville-tn-3-60-acres',
    title: '3.60 acres in Knoxville, TN',
    price: 129000,
    lotSize: '3.60 acres',
    acres: 3.6,
    city: 'Knoxville',
    state: 'TN',
    county: 'Knox',
    listedDate: '2026-08-12',
    sellerName: 'Sierra Long',
    sellerCompany: 'Smoky Mountain Parcels',
    sellerEmail: 'sierra.long@example.com',
    sellerPhone: '(919) 555-1016',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Knoxville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Knoxville market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'fort-worth-tx-8-000-sq-ft',
    title: '8,000 sq ft in Fort Worth, TX',
    price: 68000,
    lotSize: '8,000 sq ft',
    acres: 0.18,
    city: 'Fort Worth',
    state: 'TX',
    county: 'Tarrant',
    listedDate: '2026-08-11',
    sellerName: 'Caleb Turner',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'caleb.turner@example.com',
    sellerPhone: '(813) 555-1017',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Fort Worth. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Fort Worth market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'mesa-az-0-60-acres',
    title: '0.60 acres in Mesa, AZ',
    price: 155000,
    lotSize: '0.60 acres',
    acres: 0.6,
    city: 'Mesa',
    state: 'AZ',
    county: 'Maricopa',
    listedDate: '2026-08-10',
    sellerName: 'Elena Vargas',
    sellerCompany: 'Sonoran Land House',
    sellerEmail: 'elena.vargas@example.com',
    sellerPhone: '(615) 555-1018',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Mesa. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Mesa market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'huntsville-al-1-45-acres',
    title: '1.45 acres in Huntsville, AL',
    price: 76500,
    lotSize: '1.45 acres',
    acres: 1.45,
    city: 'Huntsville',
    state: 'AL',
    county: 'Madison',
    listedDate: '2026-08-09',
    sellerName: 'Marcus Hale',
    sellerCompany: 'Rocket City Land Co.',
    sellerEmail: 'marcus.hale@example.com',
    sellerPhone: '(210) 555-1019',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Huntsville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Huntsville market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'jacksonville-fl-9-400-sq-ft',
    title: '9,400 sq ft in Jacksonville, FL',
    price: 52000,
    lotSize: '9,400 sq ft',
    acres: 0.22,
    city: 'Jacksonville',
    state: 'FL',
    county: 'Duval',
    listedDate: '2026-08-08',
    sellerName: 'Tanya Price',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'tanya.price@example.com',
    sellerPhone: '(512) 555-1020',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Jacksonville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Jacksonville market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'reno-nv-2-51-acres',
    title: '2.51 acres in Reno, NV',
    price: 142000,
    lotSize: '2.51 acres',
    acres: 2.51,
    city: 'Reno',
    state: 'NV',
    county: 'Washoe',
    listedDate: '2026-07-07',
    sellerName: 'Cole Ramsey',
    sellerCompany: 'Sierra Basin Holdings',
    sellerEmail: 'cole.ramsey@example.com',
    sellerPhone: '(303) 555-1021',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Reno. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Reno market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'bozeman-mt-3-20-acres',
    title: '3.20 acres in Bozeman, MT',
    price: 389000,
    lotSize: '3.20 acres',
    acres: 3.2,
    city: 'Bozeman',
    state: 'MT',
    county: 'Gallatin',
    listedDate: '2026-07-06',
    sellerName: 'Audrey Finch',
    sellerCompany: 'Big Sky Land Advisors',
    sellerEmail: 'audrey.finch@example.com',
    sellerPhone: '(541) 555-1022',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Bozeman. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Bozeman market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'columbus-oh-5-500-sq-ft',
    title: '5,500 sq ft in Columbus, OH',
    price: 41000,
    lotSize: '5,500 sq ft',
    acres: 0.13,
    city: 'Columbus',
    state: 'OH',
    county: 'Franklin',
    listedDate: '2026-07-05',
    sellerName: 'Malik Johnson',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'malik.johnson@example.com',
    sellerPhone: '(602) 555-1023',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Columbus. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Columbus market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'oklahoma-city-ok-2-50-acres',
    title: '2.50 acres in Oklahoma City, OK',
    price: 64000,
    lotSize: '2.50 acres',
    acres: 2.5,
    city: 'Oklahoma City',
    state: 'OK',
    county: 'Oklahoma',
    listedDate: '2026-07-04',
    sellerName: 'Rachel Kim',
    sellerCompany: 'Prairie Parcel Group',
    sellerEmail: 'rachel.kim@example.com',
    sellerPhone: '(704) 555-1024',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Oklahoma City. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Oklahoma City market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'sacramento-ca-0-18-acres',
    title: '0.18 acres in Sacramento, CA',
    price: 99000,
    lotSize: '0.18 acres',
    acres: 0.18,
    city: 'Sacramento',
    state: 'CA',
    county: 'Sacramento',
    listedDate: '2026-07-03',
    sellerName: 'Victor Chen',
    sellerCompany: 'Capitol Dirt Partners',
    sellerEmail: 'victor.chen@example.com',
    sellerPhone: '(208) 555-1025',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Sacramento. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Sacramento market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'tucson-az-1-15-acres',
    title: '1.15 acres in Tucson, AZ',
    price: 48000,
    lotSize: '1.15 acres',
    acres: 1.15,
    city: 'Tucson',
    state: 'AZ',
    county: 'Pima',
    listedDate: '2026-07-02',
    sellerName: 'Leah Morgan',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'leah.morgan@example.com',
    sellerPhone: '(919) 555-1026',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Tucson. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Tucson market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'little-rock-ar-0-80-acres',
    title: '0.80 acres in Little Rock, AR',
    price: 35000,
    lotSize: '0.80 acres',
    acres: 0.8,
    city: 'Little Rock',
    state: 'AR',
    county: 'Pulaski',
    listedDate: '2026-07-01',
    sellerName: 'Derek Walsh',
    sellerCompany: 'Delta Land Finds',
    sellerEmail: 'derek.walsh@example.com',
    sellerPhone: '(813) 555-1027',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Little Rock. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Little Rock market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'madison-wi-0-52-acres',
    title: '0.52 acres in Madison, WI',
    price: 128000,
    lotSize: '0.52 acres',
    acres: 0.52,
    city: 'Madison',
    state: 'WI',
    county: 'Dane',
    listedDate: '2026-07-28',
    sellerName: 'Claire Novak',
    sellerCompany: 'Lake State Land Co.',
    sellerEmail: 'claire.novak@example.com',
    sellerPhone: '(615) 555-1028',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Madison. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Madison market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'des-moines-ia-6-000-sq-ft',
    title: '6,000 sq ft in Des Moines, IA',
    price: 29500,
    lotSize: '6,000 sq ft',
    acres: 0.14,
    city: 'Des Moines',
    state: 'IA',
    county: 'Polk',
    listedDate: '2026-07-27',
    sellerName: 'Peter Olson',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'peter.olson@example.com',
    sellerPhone: '(210) 555-1029',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Des Moines. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Des Moines market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'fayetteville-ar-2-35-acres',
    title: '2.35 acres in Fayetteville, AR',
    price: 94000,
    lotSize: '2.35 acres',
    acres: 2.35,
    city: 'Fayetteville',
    state: 'AR',
    county: 'Washington',
    listedDate: '2026-07-26',
    sellerName: 'Nina Patel',
    sellerCompany: 'Ozark Land Partners',
    sellerEmail: 'nina.patel@example.com',
    sellerPhone: '(512) 555-1030',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Fayetteville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Fayetteville market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'richmond-va-0-41-acres',
    title: '0.41 acres in Richmond, VA',
    price: 72000,
    lotSize: '0.41 acres',
    acres: 0.41,
    city: 'Richmond',
    state: 'VA',
    county: 'Henrico',
    listedDate: '2026-07-25',
    sellerName: 'Samuel Ortiz',
    sellerCompany: 'Commonwealth Parcel Co.',
    sellerEmail: 'samuel.ortiz@example.com',
    sellerPhone: '(303) 555-1031',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Richmond. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Richmond market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'salt-lake-city-ut-0-27-acres',
    title: '0.27 acres in Salt Lake City, UT',
    price: 245000,
    lotSize: '0.27 acres',
    acres: 0.27,
    city: 'Salt Lake City',
    state: 'UT',
    county: 'Salt Lake',
    listedDate: '2026-07-24',
    sellerName: 'Iris Campbell',
    sellerCompany: 'Wasatch Infill Group',
    sellerEmail: 'iris.campbell@example.com',
    sellerPhone: '(541) 555-1032',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Salt Lake City. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Salt Lake City market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'albuquerque-nm-1-00-acres',
    title: '1.00 acres in Albuquerque, NM',
    price: 39000,
    lotSize: '1.00 acres',
    acres: 1.0,
    city: 'Albuquerque',
    state: 'NM',
    county: 'Bernalillo',
    listedDate: '2026-07-23',
    sellerName: 'Mateo Ruiz',
    sellerCompany: 'High Desert Land Co.',
    sellerEmail: 'mateo.ruiz@example.com',
    sellerPhone: '(602) 555-1033',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Albuquerque. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Albuquerque market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'kansas-city-mo-0-75-acres',
    title: '0.75 acres in Kansas City, MO',
    price: 45000,
    lotSize: '0.75 acres',
    acres: 0.75,
    city: 'Kansas City',
    state: 'MO',
    county: 'Jackson',
    listedDate: '2026-07-22',
    sellerName: 'Jenna Foster',
    sellerCompany: 'Heartland Lot Buyers',
    sellerEmail: 'jenna.foster@example.com',
    sellerPhone: '(704) 555-1034',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Kansas City. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Kansas City market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'wichita-ks-1-20-acres',
    title: '1.20 acres in Wichita, KS',
    price: 38500,
    lotSize: '1.20 acres',
    acres: 1.2,
    city: 'Wichita',
    state: 'KS',
    county: 'Sedgwick',
    listedDate: '2026-07-21',
    sellerName: 'Brian Cook',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'brian.cook@example.com',
    sellerPhone: '(208) 555-1035',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Wichita. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Wichita market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'louisville-ky-0-50-acres',
    title: '0.50 acres in Louisville, KY',
    price: 68000,
    lotSize: '0.50 acres',
    acres: 0.5,
    city: 'Louisville',
    state: 'KY',
    county: 'Jefferson',
    listedDate: '2026-07-20',
    sellerName: 'Amelia Ross',
    sellerCompany: 'Bluegrass Land Co.',
    sellerEmail: 'amelia.ross@example.com',
    sellerPhone: '(919) 555-1036',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Louisville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Louisville market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'memphis-tn-7-000-sq-ft',
    title: '7,000 sq ft in Memphis, TN',
    price: 24000,
    lotSize: '7,000 sq ft',
    acres: 0.16,
    city: 'Memphis',
    state: 'TN',
    county: 'Shelby',
    listedDate: '2026-07-19',
    sellerName: 'Terrence Young',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'terrence.young@example.com',
    sellerPhone: '(813) 555-1037',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Memphis. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Memphis market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'birmingham-al-0-90-acres',
    title: '0.90 acres in Birmingham, AL',
    price: 42000,
    lotSize: '0.90 acres',
    acres: 0.9,
    city: 'Birmingham',
    state: 'AL',
    county: 'Jefferson',
    listedDate: '2026-07-18',
    sellerName: 'Sofia Martin',
    sellerCompany: 'Magic City Lots',
    sellerEmail: 'sofia.martin@example.com',
    sellerPhone: '(615) 555-1038',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Birmingham. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Birmingham market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'tulsa-ok-1-75-acres',
    title: '1.75 acres in Tulsa, OK',
    price: 56000,
    lotSize: '1.75 acres',
    acres: 1.75,
    city: 'Tulsa',
    state: 'OK',
    county: 'Tulsa',
    listedDate: '2026-07-17',
    sellerName: 'Gavin Pierce',
    sellerCompany: 'Green Country Land',
    sellerEmail: 'gavin.pierce@example.com',
    sellerPhone: '(210) 555-1039',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Tulsa. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Tulsa market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'el-paso-tx-0-33-acres',
    title: '0.33 acres in El Paso, TX',
    price: 31000,
    lotSize: '0.33 acres',
    acres: 0.33,
    city: 'El Paso',
    state: 'TX',
    county: 'El Paso',
    listedDate: '2026-07-16',
    sellerName: 'Monica Flores',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'monica.flores@example.com',
    sellerPhone: '(512) 555-1040',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in El Paso. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['El Paso market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'fort-collins-co-0-40-acres',
    title: '0.40 acres in Fort Collins, CO',
    price: 175000,
    lotSize: '0.40 acres',
    acres: 0.4,
    city: 'Fort Collins',
    state: 'CO',
    county: 'Larimer',
    listedDate: '2026-07-15',
    sellerName: 'Evan Stone',
    sellerCompany: 'Northern Colorado Dirt',
    sellerEmail: 'evan.stone@example.com',
    sellerPhone: '(303) 555-1041',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Fort Collins. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Fort Collins market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'asheville-nc-1-85-acres',
    title: '1.85 acres in Asheville, NC',
    price: 155000,
    lotSize: '1.85 acres',
    acres: 1.85,
    city: 'Asheville',
    state: 'NC',
    county: 'Buncombe',
    listedDate: '2026-07-14',
    sellerName: 'Lydia Park',
    sellerCompany: 'Blue Ridge Parcel Co.',
    sellerEmail: 'lydia.park@example.com',
    sellerPhone: '(541) 555-1042',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Asheville. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Asheville market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'eugene-or-0-65-acres',
    title: '0.65 acres in Eugene, OR',
    price: 118000,
    lotSize: '0.65 acres',
    acres: 0.65,
    city: 'Eugene',
    state: 'OR',
    county: 'Lane',
    listedDate: '2026-07-13',
    sellerName: 'Theo Bennett',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'theo.bennett@example.com',
    sellerPhone: '(602) 555-1043',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Eugene. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Eugene market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'olympia-wa-2-20-acres',
    title: '2.20 acres in Olympia, WA',
    price: 145000,
    lotSize: '2.20 acres',
    acres: 2.2,
    city: 'Olympia',
    state: 'WA',
    county: 'Thurston',
    listedDate: '2026-07-12',
    sellerName: 'Grace Lin',
    sellerCompany: 'Puget Sound Land Desk',
    sellerEmail: 'grace.lin@example.com',
    sellerPhone: '(704) 555-1044',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Olympia. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Olympia market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'flagstaff-az-2-50-acres',
    title: '2.50 acres in Flagstaff, AZ',
    price: 135000,
    lotSize: '2.50 acres',
    acres: 2.5,
    city: 'Flagstaff',
    state: 'AZ',
    county: 'Coconino',
    listedDate: '2026-07-11',
    sellerName: 'Miles Carter',
    sellerCompany: 'Ponderosa Land Group',
    sellerEmail: 'miles.carter@example.com',
    sellerPhone: '(208) 555-1045',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Flagstaff. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Flagstaff market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'macon-ga-1-25-acres',
    title: '1.25 acres in Macon, GA',
    price: 28500,
    lotSize: '1.25 acres',
    acres: 1.25,
    city: 'Macon',
    state: 'GA',
    county: 'Bibb',
    listedDate: '2026-07-10',
    sellerName: 'Aisha Coleman',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'aisha.coleman@example.com',
    sellerPhone: '(919) 555-1046',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Macon. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Macon market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'augusta-ga-0-44-acres',
    title: '0.44 acres in Augusta, GA',
    price: 36000,
    lotSize: '0.44 acres',
    acres: 0.44,
    city: 'Augusta',
    state: 'GA',
    county: 'Richmond',
    listedDate: '2026-07-09',
    sellerName: 'Frank Wilson',
    sellerCompany: 'Peach State Lots',
    sellerEmail: 'frank.wilson@example.com',
    sellerPhone: '(813) 555-1047',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Augusta. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Augusta market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'mobile-al-0-80-acres',
    title: '0.80 acres in Mobile, AL',
    price: 39500,
    lotSize: '0.80 acres',
    acres: 0.8,
    city: 'Mobile',
    state: 'AL',
    county: 'Mobile',
    listedDate: '2026-07-08',
    sellerName: 'Renee Jackson',
    sellerCompany: 'Gulf Parcel Acquisitions',
    sellerEmail: 'renee.jackson@example.com',
    sellerPhone: '(615) 555-1048',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Mobile. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Mobile market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'st-george-ut-0-55-acres',
    title: '0.55 acres in St. George, UT',
    price: 165000,
    lotSize: '0.55 acres',
    acres: 0.55,
    city: 'St. George',
    state: 'UT',
    county: 'Washington',
    listedDate: '2026-07-07',
    sellerName: 'Micah Evans',
    sellerCompany: 'Red Rock Land Co.',
    sellerEmail: 'micah.evans@example.com',
    sellerPhone: '(210) 555-1049',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in St. George. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['St. George market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'corpus-christi-tx-6-000-sq-ft',
    title: '6,000 sq ft in Corpus Christi, TX',
    price: 46500,
    lotSize: '6,000 sq ft',
    acres: 0.14,
    city: 'Corpus Christi',
    state: 'TX',
    county: 'Nueces',
    listedDate: '2026-07-06',
    sellerName: 'Natalie Cruz',
    sellerCompany: 'Coastal Bend Lots',
    sellerEmail: 'natalie.cruz@example.com',
    sellerPhone: '(512) 555-1050',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Corpus Christi. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Corpus Christi market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'chattanooga-tn-0-95-acres',
    title: '0.95 acres in Chattanooga, TN',
    price: 74000,
    lotSize: '0.95 acres',
    acres: 0.95,
    city: 'Chattanooga',
    state: 'TN',
    county: 'Hamilton',
    listedDate: '2026-07-05',
    sellerName: 'Omar Daniels',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'omar.daniels@example.com',
    sellerPhone: '(303) 555-1051',
    zoning: 'Residential acreage',
    roadAccess: 'Gravel road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Acreage homesite',
    summary: 'Seller lead for a acreage homesite in Chattanooga. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Chattanooga market', 'Gravel road', 'Acreage homesite', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'rapid-city-sd-3-00-acres',
    title: '3.00 acres in Rapid City, SD',
    price: 82000,
    lotSize: '3.00 acres',
    acres: 3.0,
    city: 'Rapid City',
    state: 'SD',
    county: 'Pennington',
    listedDate: '2026-06-04',
    sellerName: 'Bethany Shaw',
    sellerCompany: 'Black Hills Land Desk',
    sellerEmail: 'bethany.shaw@example.com',
    sellerPhone: '(541) 555-1052',
    zoning: 'Urban residential',
    roadAccess: 'Public road frontage',
    utilities: 'Power nearby; well/septic likely',
    propertyType: 'Rural acreage',
    summary: 'Seller lead for a rural acreage in Rapid City. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Rapid City market', 'Public road frontage', 'Rural acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'billings-mt-5-00-acres',
    title: '5.00 acres in Billings, MT',
    price: 69000,
    lotSize: '5.00 acres',
    acres: 5.0,
    city: 'Billings',
    state: 'MT',
    county: 'Yellowstone',
    listedDate: '2026-06-03',
    sellerName: 'Connor Blake',
    sellerCompany: 'Rimrock Acres LLC',
    sellerEmail: 'connor.blake@example.com',
    sellerPhone: '(602) 555-1053',
    zoning: 'Mixed-use potential',
    roadAccess: 'Dirt/gravel road',
    utilities: 'Water and power nearby; sewer to verify',
    propertyType: 'City lot',
    summary: 'Seller lead for a city lot in Billings. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Billings market', 'Dirt/gravel road', 'City lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'rochester-ny-0-52-acres',
    title: '0.52 acres in Rochester, NY',
    price: 33000,
    lotSize: '0.52 acres',
    acres: 0.52,
    city: 'Rochester',
    state: 'NY',
    county: 'Monroe',
    listedDate: '2026-06-02',
    sellerName: 'Ivy Walsh',
    sellerCompany: 'Individual Seller',
    sellerEmail: 'ivy.walsh@example.com',
    sellerPhone: '(704) 555-1054',
    zoning: 'Residential',
    roadAccess: 'Paved public road',
    utilities: 'Utilities nearby; taps to verify',
    propertyType: 'Residential lot',
    summary: 'Seller lead for a residential lot in Rochester. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Rochester market', 'Paved public road', 'Residential lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'harrisburg-pa-0-37-acres',
    title: '0.37 acres in Harrisburg, PA',
    price: 44500,
    lotSize: '0.37 acres',
    acres: 0.37,
    city: 'Harrisburg',
    state: 'PA',
    county: 'Dauphin',
    listedDate: '2026-06-01',
    sellerName: 'Patrick Doyle',
    sellerCompany: 'Keystone Parcel Co.',
    sellerEmail: 'patrick.doyle@example.com',
    sellerPhone: '(208) 555-1055',
    zoning: 'Residential infill',
    roadAccess: 'City street frontage',
    utilities: 'Municipal utilities nearby',
    propertyType: 'Infill lot',
    summary: 'Seller lead for a infill lot in Harrisburg. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Harrisburg market', 'City street frontage', 'Infill lot', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  },
  {
    id: 'portland-me-0-20-acres',
    title: '0.20 acres in Portland, ME',
    price: 159000,
    lotSize: '0.20 acres',
    acres: 0.2,
    city: 'Portland',
    state: 'ME',
    county: 'Cumberland',
    listedDate: '2026-06-28',
    sellerName: 'Molly Hayes',
    sellerCompany: 'Pine Coast Lots',
    sellerEmail: 'molly.hayes@example.com',
    sellerPhone: '(919) 555-1056',
    zoning: 'Rural residential',
    roadAccess: 'County road',
    utilities: 'Power nearby; water/sewer to verify',
    propertyType: 'Buildable acreage',
    summary: 'Seller lead for a buildable acreage in Portland. Treat as an opportunity record and verify ownership, availability, zoning, utilities, title, and pricing before outreach.',
    highlights: ['Portland market', 'County road', 'Buildable acreage', 'Seller contact available'],
    dueDiligence: ['Verify ownership and seller authority', 'Confirm active availability and asking price', 'Check zoning, access, utilities, and title', 'Pull current comps before making an offer'],
  }
];

export function formatLeadPrice(price: number): string {
  return price >= 1_000_000 ? `$${(price / 1_000_000).toFixed(1)}M` : `$${price.toLocaleString()}`;
}

export function formatLeadDate(value: string): string {
  const date = new Date(`${value}T00:00:00`);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}
