#!/usr/bin/env node
// Fetches the complete US county list from kjhealy/fips-codes and writes lib/countyValidation.ts

const https = require('https');
const fs = require('fs');
const path = require('path');

const CSV_URL = 'https://raw.githubusercontent.com/kjhealy/fips-codes/master/state_and_county_fips_master.csv';

function fetch(url) {
  return new Promise((resolve, reject) => {
    https.get(url, res => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => resolve(data));
      res.on('error', reject);
    }).on('error', reject);
  });
}

async function main() {
  console.log('Fetching county list from GitHub...');
  const csv = await fetch(CSV_URL);
  const lines = csv.trim().split('\n');
  const header = lines[0]; // fips,name,state
  console.log('Header:', header);
  console.log('Total rows (incl header):', lines.length);

  /** @type {Record<string, Set<string>>} */
  const byState = {};

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    const commaIdx = line.indexOf(',');
    const rest = line.slice(commaIdx + 1);
    const lastComma = rest.lastIndexOf(',');
    const name = rest.slice(0, lastComma).trim();
    const state = rest.slice(lastComma + 1).trim();

    // Skip non-county rows (state=NA means national or state-level entry)
    if (!state || state === 'NA' || state.length !== 2) continue;
    // Skip ALL-CAPS entries (state name rows in the data)
    if (name === name.toUpperCase()) continue;

    if (!byState[state]) byState[state] = new Set();
    byState[state].add(name);
  }

  const stateAbbrs = Object.keys(byState).sort();
  console.log('\nStates found:', stateAbbrs.length);
  console.log('\nCounty counts per state:');
  let total = 0;
  for (const abbr of stateAbbrs) {
    const count = byState[abbr].size;
    total += count;
    console.log(`  ${abbr}: ${count}`);
  }
  console.log(`\nTotal counties: ${total}`);

  // Spot-check a few states
  const checks = [
    ['TX', 254], ['GA', 159], ['VA', 133], ['KY', 120], ['MO', 114],
    ['KS', 105], ['IL', 102], ['NC', 100], ['IA', 99],  ['TN', 95],
    ['NE', 93],  ['IN', 92],  ['OH', 88],  ['MN', 87],  ['MI', 83],
    ['MS', 82],  ['OK', 77],  ['AR', 75],  ['WI', 72],  ['CO', 64],
    ['CA', 58],  ['AL', 67],  ['PA', 67],  ['FL', 67],
  ];
  console.log('\nSpot-check (expected vs actual):');
  for (const [abbr, expected] of checks) {
    const actual = byState[abbr]?.size ?? 0;
    const ok = actual === expected ? '✓' : `✗ (expected ${expected})`;
    console.log(`  ${abbr}: ${actual} ${ok}`);
  }

  // Build TypeScript output
  const lines_ts = [
    '// Auto-generated by scripts/generateCountyList.js — do not edit manually',
    'export const COUNTY_VALIDATION: Record<string, string[]> = {',
  ];
  for (const abbr of stateAbbrs) {
    const counties = Array.from(byState[abbr]).sort();
    const escaped = counties.map(c => `'${c.replace(/'/g, "\\'")}'`).join(', ');
    lines_ts.push(`  ${abbr}: [${escaped}],`);
  }
  lines_ts.push('};');

  const outPath = path.join(__dirname, '..', 'lib', 'countyValidation.ts');
  fs.writeFileSync(outPath, lines_ts.join('\n') + '\n');
  console.log(`\nWrote ${outPath}`);
  console.log('Done.');
}

main().catch(err => { console.error(err); process.exit(1); });
