import { NextRequest } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { createServiceClient } from '@/lib/supabase/service';
import { generatePDF } from '@/lib/generate-pdf';

export const runtime = 'nodejs';
export const maxDuration = 60;

const PAID_TIERS = new Set(['standard', 'priority', 'exclusive']);

// Downloading a report is gated the same way saving is: admin, Scout Pro, or any paid plan.
async function canDownload(userId: string): Promise<boolean> {
  const svc = createServiceClient();
  const r1 = await svc.from('profiles').select('is_admin, has_search_pro').eq('id', userId).single();
  if (!r1.error && r1.data) {
    if ((r1.data as any).is_admin || (r1.data as any).has_search_pro) return true;
  } else {
    const r2 = await svc.from('profiles').select('is_admin').eq('id', userId).single();
    if ((r2.data as any)?.is_admin) return true;
  }
  const { data: sub } = await svc.from('subscriptions').select('tier, status').eq('user_id', userId).maybeSingle();
  return !!(sub && (sub as any).status === 'active' && PAID_TIERS.has((sub as any).tier));
}

function esc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function inline(s: string): string {
  return esc(s).replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

// Lightweight markdown -> HTML: headings become bold, **bold** inline, and bullet /
// numbered lists. Mirrors the on-screen renderer.
function mdToHtml(md: string): string {
  const lines = md.replace(/\r/g, '').split('\n');
  const out: string[] = [];
  let list: string[] = [];
  let para: string[] = [];
  const flushP = () => { if (para.length) { out.push(`<p>${inline(para.join(' '))}</p>`); para = []; } };
  const flushL = () => { if (list.length) { out.push(`<ul>${list.map(li => `<li>${inline(li)}</li>`).join('')}</ul>`); list = []; } };
  for (const raw of lines) {
    const t = raw.trim();
    if (!t) { flushP(); flushL(); continue; }
    const h = t.match(/^#{1,6}\s+(.*)$/);
    if (h) { flushP(); flushL(); out.push(`<h2>${inline(h[1])}</h2>`); continue; }
    const li = t.match(/^(?:[-*]|\d+\.)\s+(.*)$/);
    if (li) { flushP(); list.push(li[1]); continue; }
    flushL(); para.push(t);
  }
  flushP(); flushL();
  return out.join('\n');
}

function slug(s: string): string {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'report';
}

function buildHtml(title: string, dateStr: string, contentHtml: string): string {
  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; }
  body { font-family: 'Manrope', 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; color: #0D1F16; }
  .header { background: #1B4332; color: #ffffff; padding: 30px 48px; }
  .brand { font-size: 24px; font-weight: 800; letter-spacing: -0.5px; }
  .brand .accent { color: #1D9E75; }
  .kicker { font-size: 11px; letter-spacing: 2px; text-transform: uppercase; color: #9FE7C7; margin-top: 6px; }
  .body { padding: 40px 48px 56px; }
  h1.title { font-size: 26px; font-weight: 800; color: #1B4332; margin: 0 0 6px; line-height: 1.2; }
  .date { font-size: 13px; color: #717973; margin: 0 0 26px; }
  .content { font-size: 15px; line-height: 1.7; color: #1f2a24; }
  .content h2 { font-size: 17px; font-weight: 800; color: #1B4332; margin: 24px 0 8px; }
  .content p { margin: 0 0 12px; }
  .content ul { margin: 0 0 14px; padding-left: 22px; }
  .content li { margin: 0 0 6px; }
  .content strong { font-weight: 700; color: #0D1F16; }
  .footer { border-top: 1px solid #e5e7eb; margin-top: 36px; padding-top: 16px; font-size: 11px; color: #9ca3af; line-height: 1.6; }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Lot<span class="accent">Scout</span></div>
    <div class="kicker">Scout Report</div>
  </div>
  <div class="body">
    <h1 class="title">${esc(title)}</h1>
    <p class="date">${esc(dateStr)}</p>
    <div class="content">${contentHtml}</div>
    <div class="footer">Generated by Scout, LotScout's real estate advisor. Educational information only, not financial, legal, or investment advice.</div>
  </div>
</body>
</html>`;
}

export async function POST(request: NextRequest) {
  const auth = await createClient();
  const { data: { user } } = await auth.auth.getUser();
  if (!user) return Response.json({ error: 'Sign in required.' }, { status: 401 });

  if (!(await canDownload(user.id))) {
    return Response.json({ error: 'Downloading reports requires a LotScout plan.' }, { status: 403 });
  }

  let body: any;
  try { body = await request.json(); } catch { return Response.json({ error: 'Invalid request' }, { status: 400 }); }

  // Strip em/en dashes so none reach the PDF.
  const rawContent = String(body?.content ?? '').replace(/\s*[—–―]\s*/g, ', ').trim().slice(0, 40000);
  const title = (String(body?.title ?? '').replace(/\s*[—–―]\s*/g, ', ').trim() || 'Scout Report').slice(0, 120);
  if (!rawContent) return Response.json({ error: 'Nothing to export.' }, { status: 400 });

  const dateStr = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const html = buildHtml(title, dateStr, mdToHtml(rawContent));

  try {
    const pdf = await generatePDF(html);
    return new Response(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="LotScout-Report-${slug(title)}.pdf"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    console.error('[advisor/pdf] generation error:', err);
    return Response.json({ error: 'Could not generate the PDF. Please try again.' }, { status: 500 });
  }
}
